"""`to_pcm16` shells out to the real ffmpeg binary, so this file legitimately
touches a subprocess (the one exception `GLOBAL_CONSTRAINTS.md` carves out)
and skips itself entirely when ffmpeg isn't on PATH, keeping CI green either way.
"""

from __future__ import annotations

import shutil
import subprocess

import pytest

from app.voice import TranscriptionError
from app.voice.audio import to_pcm16

pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None, reason="ffmpeg not on PATH"
)


@pytest.fixture
def wav_bytes() -> bytes:
    """A tiny, real, 1-second silent WAV — generated by ffmpeg itself so no
    binary fixture needs to live in the repo."""
    result = subprocess.run(
        [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=r=16000:cl=mono",
            "-t",
            "1",
            "-f",
            "wav",
            "pipe:1",
        ],
        input=b"",
        capture_output=True,
        timeout=30,
    )
    assert result.returncode == 0, result.stderr
    return result.stdout


def test_to_pcm16_returns_even_length_pcm_bytes(wav_bytes: bytes) -> None:
    pcm = to_pcm16(wav_bytes, "audio/wav")
    assert len(pcm) > 0
    assert len(pcm) % 2 == 0


def test_to_pcm16_raises_on_garbage_payload() -> None:
    with pytest.raises(TranscriptionError):
        to_pcm16(b"not audio", "audio/webm")
